# Github actions to build
# and push wheel files
name: Publish Quarto PyPi

on: 
  workflow_dispatch:
    inputs:
      production:
        description: "Production (Use PyPi, not Test.PyPi)"
        required: false
        type: boolean
        default: false
      publish-release:
        description: "Publish Release (to PyPi or Test.PyPi)"
        required: false
        type: boolean
        default: false
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Build
        run: python -m build 
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheel-files
          path: dist/*.whl
      - name: Clean Wheel
        run: rm -rf dist/quarto_cli*.whl
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ inputs.publish-release && ! inputs.production }}
        with:
          repository-url: https://test.pypi.org/legacy/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ inputs.publish-release && inputs.production }}
